### ISSUE TITLE
Some games are not working

### ISSUE THREAD

**Issue by xxxShiftUpxxx** [crazii/SBEMU#102]
I have a problem.
Some games are not working
my SET BLASTER value is "A220 I5 D1 T6"
How i can fix the issue?
![20240425_134026~2](https://github.com/crazii/SBEMU/assets/103308483/c1d8e444-efee-4ee7-a286-6e78b59a8240)

**Comment by crazii** [comment]
Hi, sorry for the delayed reply. Is I7 working for you?
which game is it? I may debug it to see the problem.

**Comment by xxxShiftUpxxx** [comment]
the error was only for this game
but i stopped playing it so you dont need to do anything.
