### ISSUE TITLE
Windows 98 error

### ISSUE THREAD

**Issue by kedesnek** [crazii/SBEMU#143]
When SBEMU is running and I try to boot into Windows 98 SE, a system protection error pops up. However, if I don't start SBEMU at all Windows boots normally.

**Comment by volkertb** [comment]
Sorry, SBEMU isn't meant to be used with Windows. It's intended to be used in pure DOS mode, as a means to getting DOS games to work with sound on systems that can still boot DOS natively, but don't have ISA slots or built-in Sound Blaster compatibility.

One approach would be to configure a boot menu in the config.sys and autoexec.bat files of your Windows 9x installation, and let it automatically load SBEMU when you pick "Boot in DOS mode". It would still require you to reboot whenever you switch between a DOS game and a Windows game.

If you really with to have Sound Blaster emulation in DOS games running inside Windows 9x, there is [a Windows 9x port of VDMSound](https://www.vogons.org/viewtopic.php?t=900) that could perhaps suit your needs. I haven't tried it myself, but maybe you can try that.

**Comment by kedesnek** [comment]
no, it's not sbemu's fault, it's just that hdpmi32i bi is turned on in
protection mode

niedz., 20 paź 2024, 14:33 użytkownik Volkert de Buisonjé <
***@***.***> napisał:

**Comment by kedesnek** [comment]
And i have on.bat
On.bat:
C:/dos/Drivers/hdpmi32i.exe
C:/dos/Drivers/sbemu.exe

pon., 21 paź 2024, 11:38 użytkownik kedesnek kedesnek ***@***.***>
napisał:
