### ISSUE TITLE
Sound latency?

### ISSUE THREAD

**Issue by jan-kleks** [crazii/SBEMU#2]
This is a really great project! Does it add sound latency due to the fact there is an additional emulation layer? If yes, how much?

**Comment by crazii** [comment]
Yes, the emulated DMA transfer may not start immediately, but after about 0~5ms.

**Comment by jan-kleks** [comment]
Hmm... I guess it is neglectable then in comparison to the latency you would get running an emulator on a modern OS.

**Comment by crazii** [comment]
I overlooked the total buffering of the PCI sound card. with the total buffering size as 16384 bytes, and with format as 16bit PCM, stereo, 22050Hz, the delay will be 0~180ms, which is noticeable.

**Comment by crazii** [comment]
the last update (beta2b) reduces the latency to an acceptable value, (10~20ms) you can try it at: https://www.vogons.org/viewtopic.php?f=62&t=93006

**Comment by jan-kleks** [comment]
This is awesome! Thank you! I think it should be totally fine now... But if there is a room of pushing it even further down without breaking SBEMU (at least on more powerful hardware) -- go for it! Of course, I mean, at some point in the future when other more important issues are ironed out...

**Comment by jan-kleks** [comment]
@crazii At this stage of the project can we theoretically reduce the buffering even further? -- For even lower latency. :)

**Comment by jan-kleks** [comment]
@crazii I see, thank you for this detailed explanation! So how does SBEMU sound latency compare to real cards it emulates?
