### ISSUE TITLE
Add compile instructions to README.md

### ISSUE THREAD

**Issue by megatog615** [crazii/SBEMU#25]
I would like to be able to compile this on my own, but I do not know how. I assume it must have something to do with the gdt and gpr files being somewhat like Makefiles, but I am unsure.

It would be nice to have instructions for building this on a DOS system directly.

**Comment by volkertb** [comment]
@megatog615 Indeed, `sbemu.gdt` and `sbemu.grp` are [RHIDE](https://sourceforge.net/projects/rhide/) project files. For more info on how to (cross-)compile this project, see [my answer](https://github.com/crazii/SBEMU/issues/22#issuecomment-1646802973) to @4nd3r50ncr, who apparently, like you and me, has been trying to figure out the same thing.

See also https://github.com/crazii/SBEMU/issues/19, in which I described my findings and work on this in further detail.

Further help is wanted in figuring out how to get the `Makefile` generated by `GPR2MAK.EXE` to work!

**Comment by crazii** [comment]
Now that the makefile of thp is merge, you can build it in Linux with DJGPP toolchains, or WSL in Windows.
