### ISSUE TITLE
Compile new version fixed.

### ISSUE THREAD

**Issue by 4nd3r50ncr** [crazii/SBEMU#32]
@thp hello, can you help me compile with your new form?

**Comment by thp** [comment]
If you're just interested in the SIS7012 support, a binary is available at https://github.com/thp/sbemu/releases/tag/1.0beta3-sis7012

To build, you just need to have a recent DJGPP version installed (this build script works quite well: https://github.com/andrewwutw/build-djgpp) and then just clone the repo with the right branch/tag and type "make".

**Comment by 4nd3r50ncr** [comment]
Hello @thp, I noticed that you are very active on the Vogons forum, you have a close relationship with the members there. in fact sbemu is very important, but it seems a bit abandoned and without a license specification, I think that as you embraced the project you could add the license specification in your README, or LICENSE. I've been doing extensive testing for both FreeDOS and EDR-DOS on a real machine via an SD/USB card on modern machines, I believe that on older machines it also works via the USB port, so this is the best way to test SBEMU in real mode on the computer.

**Comment by wxpc8** [comment]
> If you're just interested in the SIS7012 support, a binary is available at https://github.com/thp/sbemu/releases/tag/1.0beta3-sis7012
> 
> To build, you just need to have a recent DJGPP version installed (this build script works quite well: https://github.com/andrewwutw/build-djgpp) and then just clone the repo with the right branch/tag and type "make".

Hi thp, you're amazing, and I've followed you. Thank you for your contributions to the sbemu project. my SiS 7012 integrated sound card is now working in DOS. However, your modified version and the original sbemu version seem to have the same issue. When running the DOS version of the 90s hit real-time strategy game "Command & Conquer: Red Alert 95," the game crashes with a black screen after just a few minutes of gameplay. I've posted the problem and photos of the error codes at the following link, and I hope you can try running the game when you have some free time.

I have several mini PC hosts, including Intel HDA, VIA 7012, and others, all supported by sbemu software, and I've tested them all. Whether it's the original sbemu version or sbemu-7012, and regardless of the AC97 sound card used, I get the same results. However, installing a PCI standalone sound card or muting the game makes it run perfectly stable. Therefore, I believe this issue is caused by a bug in sbemu.

https://github.com/crazii/SBEMU/issues/34#issue-1958535946

**Comment by 4nd3r50ncr** [comment]
Hello friend, the likely cause of the error you are receiving could be from jemmex, try using qemm. If you are using FreeDOS, its command is not 100% compatible with everything, test it on another DOS system.

**Comment by wxpc8** [comment]
> 您好朋友，您收到的错误的可能原因可能来自 jemmex，请尝试使用 qemm。如果您使用 FreeDOS，它的命令并不是 100% 兼容所有内容，请在另一个 DOS 系统上测试它。



> Hello friend, the likely cause of the error you are receiving could be from jemmex, try using qemm. If you are using FreeDOS, its command is not 100% compatible with everything, test it on another DOS system.

Thank you. I used "device=qemm386.sys ram" and ran "ra.exe", but I still encountered the same black screen error.

**Comment by wxpc8** [comment]
> Hello friend, the likely cause of the error you are receiving could be from jemmex, try using qemm. If you are using FreeDOS, its command is not 100% compatible with everything, test it on another DOS system.

Thank you. I used "device=qemm386.sys ram" and ran "ra.exe", but I still encountered the same black screen error.

**Comment by crazii** [comment]
> but it seems a bit abandoned and without a license specification

Sorry to make you feel that way, but it's not abandoned . I'll get back about next year.
I'm on vacation and the international network is f**ked up in my country and I currently have no VPN, and the access to Github is just by luck, for most of the time, it cannot be opened.

**Comment by crazii** [comment]
> but it seems a bit abandoned and without a license specification

Sorry to make you feel that way, but it's not abandoned . I'll get back about next year.
I'm on vacation and the international network is f**ked up in my country and I currently have no VPN, and the access to Github is just by luck, for most of the time, it cannot be opened. I cannot post a comment normally.

**Comment by 4nd3r50ncr** [comment]
Alright, no problem, friend! I know that in your country the firewall is complicated, I understand. We're here together, we need to find a way to remove mpxplay, it's not a welcome license, or a friendly one, we need to share this freely, it's a free project, and I think it's beautiful, since the beginning of Unix, and all the free software movement etc. We are always here, to help, I always participate in free projects, not here through github, but through other sites, this is the first one here, anyway, we are here. See you later friend.

**Comment by volkertb** [comment]
@crazii Your work on this is very much appreciated, especially with the additional challenges you are currently facing. Thank you!

Another question: is it currect that [v5.84pre2](https://github.com/Baron-von-Riedesel/Jemm/releases/tag/v5.84pre2) is the minimum version of Jemm that is required for SBEMU to work? That might explain why some people have been having problems getting SBEMU to work with Jemm.

Thanks again!

**Comment by crazii** [comment]
> @crazii Your continued work on this is very much appreciated, especially with the additional challenges you are currently facing. Thank you!
> 
> Another question: is it correct that [v5.84pre1](https://github.com/Baron-von-Riedesel/Jemm/releases/tag/v5.84pre1) or [v5.84pre2](https://github.com/Baron-von-Riedesel/Jemm/releases/tag/v5.84pre2) is the minimum version of Jemm that is required for SBEMU to work? That might explain why some people have been having problems getting SBEMU to work with Jemm.
> 
> Thanks again!

Yes, and according to the description, v5.84pre2 is preferred.

**Comment by volkertb** [comment]
I will update my PR to pull that version in. Easiest would be to overwrite it in the USB image in-place.
