### ISSUE TITLE
run game crash

### ISSUE THREAD

**Issue by wxpc8** [crazii/SBEMU#34]
sorry!My computer bad.sbemu work ok

**Comment by wxpc8** [comment]
I have tested multiple computers with varying physical memory sizes (256MB, 512MB, 1GB, or 2GB) and different central processing units (ranging from 500MHz to 1200MHz). The sound cards used include both Intel and Realtek AC97, which are supported by SBEmu and capable of producing sound. As for the operating system, I have tried both FreeDOS and MS-DOS 6.22, using either HIMEM.SYS or JEMMEX in the CONFIG.SYS file. However, in all cases, the same crash occurs after a few minutes of running Command & Conquer: Red Alert.

To capture the error message that flashes on the screen during the crash, I recorded a video and extracted a screenshot from it. From the screenshot, it can be seen that the initial error message displayed is "hdpmi: fatal exit 0007." This is followed by numerous codes resembling memory addresses. The first error message that appears is "Exception 0D in ring 0." I have attached the screenshot and would appreciate if any experts could examine it to determine the cause of the issue.

![mmexport1699947198097](https://github.com/crazii/SBEMU/assets/148545871/a93a3355-8d45-448d-8f0e-0d549548bb68)

![Uploading mmexport1699947212321.png…]()

**Comment by wxpc8** [comment]
I have found that even when running Oracle VM VirtualBox virtual machine on a Windows 10 computer, installing a DOS system, virtualizing an AC97 integrated sound card, the same phenomenon occurs when running RedAlert95.

**Comment by crazii** [comment]
Thanks for the feedback, I need investigate the problem.

**Comment by wxpc8** [comment]
> Thanks for the feedback, I need investigate the problem.

Thank you very much. I'm sorry to disturb you. Thank you for taking the time to reply to the post during your vacation. I am deeply moved. I have never had such a close communication with an author before. I am not in a hurry to fix these bugs, as I believe it will be an easy task for you. The most important thing now is for you to enjoy your vacation.

**Comment by wxpc8** [comment]
sorry,my computer bad.sbemu work ok!
