### ISSUE TITLE
SoundBlaster AudioPCI128 (CT4810) (CT2518/ES1371/ES1373) locks up when initializing

### ISSUE THREAD

**Issue by MFDGaming** [crazii/SBEMU#41]
When initializing the driver, in some motherboards it straight up locks up and in other ones it produces a noisy sound and if any program that uses sound gets launched it locks up. (the soundcards (yes i have 2 of them) and motherboards are fully functional as they work with the creative drivers and with mpxplay alone)

**Comment by JoshuaSchaferhund94** [comment]
Yeah, this is the same problem I've had in VMware when using the emulated ES1371 card. It's a shame because I would like to play some games using Windows 9x's functionality to reboot in a custom DOS configuration with SBEMU loaded since SBEMU offers better OPL emulation than VDMSound, and there's no real Intel HD audio drivers that exist for Windows 98 other than some weird Windows 3.1 specific drivers that are really difficult to get working (and even then I doubt that it would utilize features like DirectSound or SBEMUL.SYS.)

**Comment by MFDGaming** [comment]
> The [website focused on Win3.1 drivers](http://turkeys4me.byethost4.com/index.htm) has [Creative AudioPCI ens1371/1373 driver Version 2.0](http://turkeys4me.byethost4.com/programs/ENS137X2.ZIP)

I personally have the original driver CD, the issue is that the original dos driver has awful SB emulation and does not work well with all motherboards

**Comment by crazii** [comment]
I just update the ES1371 driver, enabling interrupt and adding IRQ handler, now it should work, but need test to confirm.

**Comment by MFDGaming** [comment]
> I just update the ES1371 driver, enabling interrupt and adding IRQ handler, now it should work, but need test to confirm.

thanks, i am gonna test as soon as possible on real hardware

**Comment by MFDGaming** [comment]
Works well when manually specifying the output (/O). For some reason when not specifying it defaults to 1 instead of 0 which make all programs with audio to crash if not changed. Also for some reason when changing the output while the driver is already running will cause the audio to become choppy.

**Comment by crazii** [comment]
/O option only apply to intel HDA, are you testing with a HDA sound card or ES1371?
you can confirm with /SCL  option, it only works before TSR

**Comment by MFDGaming** [comment]
> /O option only apply to intel HDA, are you testing with a HDA sound card or ES1371? you can confirm with /SCL option, it only works before TSR

that computer i used doesnt even have HDA

**Comment by MFDGaming** [comment]
even when it inited it said ensoniq

**Comment by MFDGaming** [comment]
i guess ill test again and record it on video

**Comment by vicokoby** [comment]
I'm not sure if I should comment here, but I tested SBEMU with my Creative CT4740 sound card which I understand has an ES1373 chip, the card is recognized correctly, however no sound is heard even using /VOL9.

![CT4740](https://github.com/crazii/SBEMU/assets/9407044/8a65daf9-2ba9-48bb-a9ee-a1371e807fed)

I also want to mention that using MPXPLAY 1.67, something similar happens, the sound card is recognized but audio files cannot be played.

**Comment by MFDGaming** [comment]
OK it seems the /O0 thing I said was a coincidence, after disabling the parallel port and reserved IRQ 7 & 5 in the bios it seems to consistently work without adding /O0

**Comment by crazii** [comment]
Cool, I'll close this issue. you can reopen it anytime if you found problem with it.
