### ISSUE TITLE
Merge changes from SBEMU-X

### ISSUE THREAD

**Issue by Torinde** [crazii/SBEMU#45]
There are some features added in SBEMU-X not yet merged into SBEMU. Also the README has some additional info.

I tried [comparing both projects](https://github.com/crazii/SBEMU/compare/main...sbemu-x:sbemu-x:main), but it seems some changes that _were_ implemented in SBEMU are still highlighted by Github, so probably I'm not using properly the compare/merge function.

**Comment by thp** [comment]
Once #51 and #52 are merged, there shouldn't be anything substantial left from SBEMU-X apart from code style, naming (SBEMU-X vs SBEMU) and SBEMU-X has the files for I/O trapping moved into a `iotrap/` folder (not really necessary, of course).

**Comment by volkertb** [comment]
@thp Actually, isolating the I/O trapping code into a separate folder may be useful when we make another attempt to port SBEMU to the port-trapping API that @Baron-von-Riedesel [implemented in the upstream version of HDPMI32i](https://github.com/Baron-von-Riedesel/HX/commit/2f18ab8cdf9e30ce1d8812798b7e47af8f9684f1) for the VSBHDA project. So good job!

**Comment by crazii** [comment]
done.

**Comment by crazii** [comment]
> @thp Actually, isolating the I/O trapping code into a separate folder may be useful when we make another attempt to port SBEMU to the port-trapping API that @Baron-von-Riedesel [implemented in the upstream version of HDPMI32i](https://github.com/Baron-von-Riedesel/HX/commit/2f18ab8cdf9e30ce1d8812798b7e47af8f9684f1) for the VSBHDA project. So good job!

I don't think it helps much on that but put them in a separate folder is a good idea anyways.

**Comment by thp** [comment]
Archived the [sbemu-x repo](https://github.com/sbemu-x/sbemu-x) now. Thanks for merging the changes upstream :) I think this can be closed.
