### ISSUE TITLE
HDA driver for Win9x

### ISSUE THREAD

**Issue by Torinde** [crazii/SBEMU#61]
SBEMU won't work on any windows system by its nature - windows has its own DPMI host and it have no port trapping, and windows won't launch if there's a DPMI installed under DOS (e.g. HDPMI32i)

_Originally posted by @crazii in https://github.com/crazii/SBEMU/issues/59#issuecomment-1866187246_

Some Win9x games and software benefit from running on bare metal (CPU speed/compatibility) and keeping aside the GPU (e.g. using old PCIe card with Win9x drivers or [SoftGPU-llvmpipe](https://github.com/JHRobotics/softgpu)) - it'll help if for the audio the modern hardware can be utilized (without resorting to PCIe-to-PCI adapters).

Can the code in SBEMU help to create HDAudio driver for Win9x?
Or does somebody have other ideas how to run Win9x on modern hardware?

**Comment by crazii** [comment]
SBEMU can be a VXD to work in win9x, it's best with a dpmi host supports VXD so that SBEMU will work for both win9x and DOS.

**Comment by albertus82** [comment]
> * [Windows 3.1/95/98/ME HDA Driver](https://retrosystemsrevival.blogspot.com/2019/06/windows-31959898se-hda-driver.html)

Hi, I tried the driver above and, while appreciating the effort of the developer, I must say it's far from perfect. It always hangs the system when opening as dos prompt inside Windows, and sometimes crashes Windows for unknown reasons while playing sounds.

I really think the only viable way to achieve good results is to emulate SB16 the same way SBEMU does under DOS.
