### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by sparky4** [crazii/SBEMU#8]
how dose one even compile the emulator?

**Comment by crazii** [comment]
Currently it compiles in DOS (real machine or VM like vbox/vmware).
You need DOSLFN (http://adoxa.altervista.org/doslfn/) and DJGPP with RHIDE (https://www.delorie.com/djgpp/)
The repo already includes a RHIDE project file, run rhide in the root folder and it will open.

**Comment by sparky4** [comment]
thank you! <3 keep it up

**Comment by sparky4** [comment]
how do i install rhide and djgpp?

**Comment by crazii** [comment]
Use the 'zip picker' in the djgpp site and choose “build djgpp programs" and os="dos", editor =“rhide” then download the zips in the list populated.
Unzip all the zips to a single location, i.e c:\djgpp
Add c:\djgpp\bin to PATH
Set DJDIR=c:\djgpp
Set DJGPP=c:\djgpp\djgpp.env
And it's done.
I don't remember but there should be manuals/readmes on the djgpp site.

**Comment by volkertb** [comment]
@crazii I've tried using `GPR2MAK.EXE` (which comes with RHIDE) to convert `sbemu.gpr` to a standard UNIX-stile Makefile. But unfortunately, the generated Makefile doesn't work. I've instead run the RHIDE build process in slow motion in a VM, during which I made notes of the build commands that briefly appeared on the screen during the build, and then I made a cross-compilation script based on that. But just having the `sbemu.gpr` as the "single source of truth" in terms of building the project, with automated (cross-)compilations being done through `GPR2MAK.EXE`, would of course be preferable.

Can you maybe help with this?

See my posts in this thread for my findings, steps and challenges so far: https://github.com/crazii/SBEMU/issues/19

Thanks!
