### ISSUE TITLE
Works really good in general... but not in MPXPLAY (static noise at full blast)

### ISSUE THREAD

**Issue by Ethaniel-404** [crazii/SBEMU#87]
I honestly don't get it. I have sound in Descent, FastDoom (with some tweaks), and Carmen Sandiego in Space, but MPXPLAY refuses to cooperate. With the default config, MPXPLAY makes no sounds, but if I use the -scc 1 modifier to reroute audio to internal speakers, all I get is static at max volume (I almost died of a heart attack the first time).

I mean, it's not that important, really. My netbook's speakers are tiny pieces of crap anyway, but maybe you have an idea about this...? Thanks as always.

**Comment by hjnijlunsing** [comment]
Why are you using MPXPLAY with SBEMU? What sound card are you using? Isn't it supported in MPXPLAY directly?

**Comment by Ethaniel-404** [comment]
> Why are you using MPXPLAY with SBEMU? What sound card are you using? Isn't it supported in MPXPLAY directly?

That is what irks me the most: It's just an Intel HDA chip, and MPXPLAY it should support it... but I never got any sound directly. I'll keep testing, but my best result so far was the «evil static of death» with SBEMU loaded. Any ideas are welcome.

**Comment by crazii** [comment]
So you run mpxplay directly without sbemu and you ain't getting any sounds?
That's possible, because mpxplay uses only PIO mode for HDA, but as I talked to the author last time, I think it will be fixed for next release.

If you run mpxplay with SBEMU, then I don't know the results because I never tested it.

**Comment by Ethaniel-404** [comment]
> So you run mpxplay directly without sbemu and you ain't getting any sounds? That's possible, because mpxplay uses only PIO mode for HDA, but as I talked to the author last time, I think it will be fixed for next release.
> 
> If you run mpxplay with SBEMU, then I don't know the results because I never tested it.

Sounds reasonable. Mpxplay hasn't received an update in more than six months, so... patience then. Too bad [DSS (Digital Sound System)](https://www.vgmpf.com/Wiki/index.php/Digital_Sound_System) doesn't detect SBEMU either, that would be enough for me to play MP3s.

**Comment by crazii** [comment]
I think the music players could be supported, but currently would be in low priority, I will check it when have more time available. Or it will be good if anyone helps with that - debugging and coding etc.
