### ISSUE TITLE
DIR Command working very slow in secondary disk driver

### ISSUE THREAD

**Issue by mgoulartBR** [crazii/SBEMU#94]
I'm facing a issue after initiate SBEMU (2024.03.01_17-53) on Freedos 1.3.

I can access my secondary disk driver (D:) but if I try to run DIR command, my Freedos takes a lot of time to execute.
My disk is a SATA SSD disk with 512GB full of folders and games. When SBEMU isn't loaded, the DIR command runs normally.

**Comment by mgoulartBR** [comment]
Actually DIR command is also slow in my primary disk driver

**Comment by mgoulartBR** [comment]
UserBuild 2024.03.01_17-53

Em seg., 18 de mar. de 2024 21:57, crazii ***@***.***>
escreveu:

**Comment by crazii** [comment]
Does it happen before? There's some changes recently.
It's probable that the shared IRQ is not handled properly. I also made some changes in HDPMI that HW interrupts may not respond right immediately.

**Comment by mgoulartBR** [comment]
I tested UserBuild_2024.03.01_17-53, UserBuild_2024.02.27_14-01,
UserBuild_2024.01.24_20-23 and 1.0 beta3.

Only in 1.0 beta3 I could use my FreeDos normally after loading SBEMU.

**Comment by crazii** [comment]
Can you test if this custom builds works? I've temporarily turned off the code changes in HDPMI.
Use the 2 files in the zip along with the original JEMMEX if it's used.
[SBEMU.zip](https://github.com/crazii/SBEMU/files/15103188/SBEMU.zip)

**Comment by mgoulartBR** [comment]
I tested using 1.0-beta4, it's working fine now!

**Comment by crazii** [comment]
Cool, but I don't know what actually happens, maybe some bugs are fixed recent changes.
I'll close this issue and you can reopen it if any problem found.
